FROM golang:1.17-alpine

WORKDIR /app

# Copia o código fonte para o diretório de trabalho
COPY . .

# Compila o programa
RUN go build -o main .

# Define o comando padrão a ser executado quando o container for iniciado
CMD ["./main"]
